name: 'cargo-build'
description: 'Run a cargo command and parse its output'
author: 'Tiwalun'
inputs:
  command: 
    required: true
    description: 'cargo subcommand'
  arguments:
    required: false
    description: 'arguments to subcommand'
runs:
  using: 'node16'
  main: 'dist/index.js'
